---
name: Docker CI/CD for Gallery
'on':
  push:
    paths:
      - gallery/**
    branches:
      - main
jobs:
  Set-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
  Unit-Test:
    needs:
      - Set-Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests
          pip install -r gallery/app/requirements.txt
      - name: Test gallery
        run: |
          pytest -v ./gallery/tests/ --doctest-modules --junitxml=junit/test-results-gallery.xml
      - name: Upload gallery pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-gallery
          path: junit/test-results-gallery.xml
        if: ${{ always() }}
  Build_and_Push:
    needs:
      - Set-Dependencies
      - Unit-Test
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./gallery
          file: ./gallery/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: craigallerydev001.azurecr.io/dstoolkitaiux:latest